#!/bin/bash

# DockerHub hook to push extra images to the repo on build. Assumes the
# ":latest" tagged version is always pushed automatically.

imageName="${DOCKER_REPO}"

# Get tag for image, and parse into parts: the before first "-" part (the tool
# version) and the after first "-" part (the build version).
read TAG < "TAG"
contentVersion="${TAG%%-*}"
sourceVersion="${TAG#*-}"

###
# Do the actual push
###

docker push "${imageName}:${contentVersion}"
docker push "${imageName}:${contentVersion}-${sourceVersion}"
